In [1]:
# Python libs
import pandas as pd

# Magics
from helpers import (
    load_sql_magic,
)
load_sql_magic()          # %%sql   — query DataFrames via duckdb (no extra installs)

True

In [2]:
import duckdb

DB_PATH = "./data/ab_events.duckdb"

con = duckdb.connect(DB_PATH, read_only=True)
event_log = con.execute("SELECT * FROM events").df()
con.close()

print(event_log.shape)
event_log.head()

(2024484, 7)

,date,user_id,hash_id,country,experiment,event_type,amount
0,2025-01-01 21:01:12,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
1,2025-01-01 21:02:09,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
2,2025-01-01 14:45:14,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
3,2025-01-01 14:46:03,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
4,2025-01-01 22:36:08,7,1750302349509622455,US,"{""num01"":""a""}",page_view,NaN

In [3]:
with duckdb.connect(DB_PATH, read_only=True) as con:
    df = con.execute("SHOW tables").df()

print(df)

     name
0  events

In [4]:
%%sql

SELECT * FROM event_log

,date,user_id,hash_id,country,experiment,event_type,amount
0,2025-01-01 21:01:12,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
1,2025-01-01 21:02:09,5,7674613650421074157,US,"{""num01"":""a""}",page_view,NaN
2,2025-01-01 14:45:14,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
3,2025-01-01 14:46:03,6,1310192797669293303,GB,"{""num01"":""a""}",page_view,NaN
4,2025-01-01 22:36:08,7,1750302349509622455,US,"{""num01"":""a""}",page_view,NaN
...,...,...,...,...,...,...,...
2024479,2025-02-28 23:19:03,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024480,2025-02-28 23:19:44,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024481,2025-02-28 23:20:04,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024482,2025-02-28 23:21:08,25000,4860591953457782041,GB,"{""num01"":""a""}",page_view,NaN
2024483,2025-02-28 23:24:40,25000,4860591953457782041,GB,"{""num01"":""a""}",watch,NaN